version: "2"
services:
  db:
    container_name: studentdb_container_next
    image: mysql:5.7
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: studentdb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: ./app
    links:
      - db
    ports:
      - "5001:5000"
    depends_on:
      - db
  next-app:
    build: ./next-app
    links:
      - app
    ports:
      - "3000:3000"
    depends_on:
      - app
      