version: "2"
services:
  db:
    container_name: studentdb_flask_container
    image: mysql:5.7
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: studentdb_flask
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  app:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
    depends_on:
      - db
      