version: "2"
services:
    mysql-development:
        container_name: employeedb_container
        image: mysql:8.0.17
        ports:
          - "3307:3306"
        environment:
          MYSQL_ROOT_PASSWORD: root_pass
          MYSQL_DATABASE: employeedb
        volumes:
          - ./init.sql:/docker-entrypoint-initdb.d/init.sql
